GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Third Post",
  "author": "Anton",
  "url": "http://bababa.com",
  "likes": 7
}