GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Fifth",
  "author": "Anton",
  "url": "http://bababa.com",
  "likes": 7
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "lthegreatish",
  "name": "Ludwig The Greatishest",
  "password": "126"
}